name: Build iOS IPA
on: [push]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: pod install

      - name: Build App
        run: |
          xcodebuild build \
            -workspace 'Sample.xcworkspace' \
            -scheme 'Sample' \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            ENABLE_USER_SCRIPT_SANDBOXING=NO \
            -allowProvisioningUpdates=NO

      - name: Package IPA
        run: |
          mkdir -p Payload
          # Updated path specifically for Xcode 16's folder structure
          cp -R build/Build/Products/Release-iphoneos/Sample.app Payload/
          zip -r Sample.ipa Payload
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: Sample.ipa
